name: Check package

on:
  workflow_call:

jobs:
  check-python:
    runs-on: ubuntu-latest
    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@5ef0c079ce82195b2a36a210272d6b661572d83e # v2.14.2
        with:
          egress-policy: audit

      - name: Checkout repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Install uv
        uses: astral-sh/setup-uv@eac588ad8def6316056a12d4907a9d4d84ff7a3b # v7.3.0

      - name: Install justfile
        run: sudo apt-get install -y just

      - name: Install Python
        uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405 # v6.2.0
        with:
          python-version-file: "pyproject.toml"

      - name: Install the project and it's dependencies
        run: just install-deps

      - name: Check Python style
        run: just check-python

      - name: Run tests and coverage
        run: just test-python

      - name: Prepare repo for coverage report
        run: |
            # So that folder can be committed
            rm htmlcov/.gitignore

      - name: Push coverage report and badge to branch
        uses: JamesIves/github-pages-deploy-action@d92aa235d04922e8f08b40ce78cc5442fcfbfa2f # v4.8.0
        with:
          branch: coverage
          folder: htmlcov
          # Keep a simple Git history
          single-commit: true

      - name: Run security checks
        run: just check-security

      - name: Run spell checker
        run: just check-spelling

      - name: Run unused code checker
        run: just check-unused
