name: Test template
on:
  workflow_call:
    inputs:
      # The justfile recipe that will run the template tests.
      test-recipe:
        type: string
        required: true

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@df199fb7be9f65074067a9eb93f12bb4c5547cf2 # v2.13.3
        with:
          egress-policy: audit

      - name: Checkout
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8

      - name: Set up uv
        uses: astral-sh/setup-uv@1e862dfacbd1d6d858c55d9b792c756523627244
        with:
          enable-cache: true

      - name: Install justfile
        run: sudo apt install -y just

      - name: Set Git user
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "fake@example.com"

      - name: Test and check template creation
        run: just ${TEST_RECIPE}
        env:
          TEST_RECIPE: ${{ inputs.test-recipe }}
