name: Check package

on:
  workflow_call:

jobs:
  check-python:
    runs-on: ubuntu-latest
    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@20cf305ff2072d973412fa9b1e3a4f227bda3c76 # v2.14.0
        with:
          egress-policy: audit

      - name: Checkout repository
        uses: actions/checkout@1af3b93b6815bc44a9784bd300feb67ff0d1eeb3 # v6.0.0

      - name: Install uv
        uses: astral-sh/setup-uv@1e862dfacbd1d6d858c55d9b792c756523627244 # v7.1.4

      - name: Install justfile
        run: sudo apt-get install -y just

      - name: Install Python
        uses: actions/setup-python@83679a892e2d95755f2dac6acb0bfd1e9ac5d548 # v6.1.0
        with:
          python-version-file: "pyproject.toml"

      - name: Install the project and it's dependencies
        run: just install-deps

      - name: Check Python style
        run: just check-python

      - name: Run tests and coverage
        run: just test-python

      - name: Prepare repo for coverage report
        run: |
            # So that folder can be committed
            rm htmlcov/.gitignore

      - name: Push coverage report and badge to branch
        uses: JamesIves/github-pages-deploy-action@4a3abc783e1a24aeb44c16e869ad83caf6b4cc23 # v4.7.4
        with:
          branch: coverage
          folder: htmlcov
          # Keep a simple Git history
          single-commit: true

      - name: Run security checks
        run: just check-security

      - name: Run spell checker
        run: just check-spelling

      - name: Run unused code checker
        run: just check-unused
